# Generated by Django 3.1.3 on 2021-01-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(max_length=13)),
                ('alternate_contact_number', models.CharField(max_length=13)),
                ('relationship_of_alternate_contact_person', models.CharField(max_length=20)),
                ('current_location', models.CharField(max_length=20)),
                ('current_address', models.TextField()),
                ('git_link', models.TextField()),
                ('college_name', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=20)),
                ('degree_stream', models.CharField(max_length=20)),
                ('degree_percentage', models.FloatField(max_length=5)),
                ('degree_graduation_year', models.IntegerField(max_length=5)),
                ('masters', models.CharField(blank=True, max_length=20, null=True)),
                ('masters_stream', models.CharField(blank=True, max_length=20, null=True)),
                ('masters_percentage', models.FloatField(blank=True, max_length=5, null=True)),
                ('year_of_job_experience', models.IntegerField(blank=True, max_length=50, null=True)),
                ('year_of_masters', models.IntegerField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
