# Generated by Django 3.1.5 on 2021-02-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='note_images/'),
        ),
    ]
