get_response = [
    {
        "Id": 1,
        "Name": "Astroboy",
        "phone number": 9876543210,
        "Alternate contact number": 9517538524,
        "Relation ship of alternate contact person": "Parent",
        "Current Location": "Delhi",
        "Current Address": "170, Ber Sarai, Hauz Khas, Delhi",
        "GIT Link": "github.com/astroboy",
        "College Name": "IIIT Bhubaneswar",
        "University": "IIIT Bhubaneswar",
        "Degree": "B.Tech",
        "Degree Stream": "CS",
        "Degree %": 70,
        "Degree Passing Yr": 2019,
        "Masters, Stream": "AI",
        "Masters %": 77,
        "Yr of Masters": 2023,
        "Yr of Exp": 1
    },
    {
        "Id": 2,
        "Name": "Doraemon",
        "phone number": 9638527410,
        "Alternate contact number": 9874563210,
        "Relation ship of alternate contact person": "Guardian",
        "Current Location": "Noida",
        "Current Address": "118, Sector 62, Gautam Buddha Nagar, Noida",
        "GIT Link": "github.com/doraemon",
        "College Name": "IIIT Hyderabad",
        "University": "IIIT Hyderabad",
        "Degree": "B.Tech",
        "Degree Stream": "IT",
        "Degree %": 85,
        "Degree Passing Yr": 2019,
        "Masters, Stream": "CS",
        "Masters %": 82,
        "Yr of Masters": 2022,
        "Yr of Exp": 0
    },
    {
        "Id": 3,
        "Name": "Optimus",
        "phone number": 9123654789,
        "Alternate contact number": 9876541230,
        "Relation ship of alternate contact person": "Parent",
        "Current Location": "Hyderabad",
        "Current Address": "625, Mantri Celestia, ISB road, Gachibowli, Hyderabad",
        "GIT Link": "github.com/optimusprime",
        "College Name": "IIIT Bangalore",
        "University": "IIIT Bangalore",
        "Degree": "B.Des",
        "Degree Stream": "Fashion Technology",
        "Degree %": 86,
        "Degree Passing Yr": 2020,
        "Masters, Stream": "",
        "Masters %": "",
        "Yr of Masters": "",
        "Yr of Exp": 0
    },
    {
        "Id": 4,
        "Name": "Ratchet",
        "phone number": 9431675280,
        "Alternate contact number": 9073164258,
        "Relation ship of alternate contact person": "Brother",
        "Current Location": "Bangalore",
        "Current Address": "216, Atlantis, Electronic City, Phase -I, Bangaluru",
        "GIT Link": "github.com/Ratchet",
        "College Name": "IIT Bhu",
        "University": "Banaras Hindu Univerity",
        "Degree": "B.Tech",
        "Degree Stream": "ECE",
        "Degree %": 89,
        "Degree Passing Yr": 2018,
        "Masters, Stream": "",
        "Masters %": "",
        "Yr of Masters": "",
        "Yr of Exp": 0
    },
    {
        "Id": 5,
        "Name": "Doom",
        "phone number": 9371862405,
        "Alternate contact number": 9416872503,
        "Relation ship of alternate contact person": "Parent",
        "Current Location": "Chennai",
        "Current Address": "216, MGR Road, Tharamani, Chennai",
        "GIT Link": "github.com/doom",
        "College Name": "CMI",
        "University": "CMI",
        "Degree": "B.Sc",
        "Degree Stream": "Mathematics",
        "Degree %": 84,
        "Degree Passing Yr": 2019,
        "Masters, Stream": "Statistics",
        "Masters %": 83,
        "Yr of Masters": 2022,
        "Yr of Exp": 1
    }
]
